### ISSUE TITLE
Use domains, rather than domains with subdomains, when checking history

### ISSUE THREAD

**Issue by cdeevfrr** [Tyler-Murphy/New-Site-Warning-browser-extension#2]
right now, subdomains are considered when deciding if a site has been visited.

This should be only domains, but probably configurable.

**Comment by Tyler-Murphy** [comment]
We should think more about whether this is safe. I just remembered that many hosting platforms give you a subdomain of their domain for free so that you don't have to get your own domain. Which means that a trusted domain could be running untrusted code on its subdomains. I wouldn't be surprised if phishing sites are more likely to work this way, so that they don't have to buy domain names.

**Comment by Tyler-Murphy** [comment]
I'm going to close it for now, but we should reopen if we decide that this is a good idea.
